export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
export const decisionOption = "//span[text()='Decisão']"
export const decisionSelectDate = "//input[@placeholder='Selecionar data']"
export const decisionValue = "//input[@id='ValorDeferido']"
export const decisionLabel = "(//label[text()='Decisão']/following::input)[1]"
export const selectAgree = "//div[contains(text(),'Acordo')]"
export const decisionTextArea = "//label[text()='Descrição']/following::textarea"
export const decisionSaveButton = "//span[text()='Salvar']"
export const decisionTimelineLink = "(//b[text()='Decisão'])[1]"
export const decisionDeleteButton = "//span[text()='Excluir']"

