export const decisionSelectDate = "//input[@placeholder='Selecionar data']"
export const decisionValue = "//input[@id='ValorDeferido']"
export const decisionLabel = "//input[@id='Decisao']"
export const selectAgree = "//div[contains(text(),'Acordo')]"
export const decisionTextArea = "//label[text()='Descrição']/following::textarea"
export const decisionSaveButton = "//span[text()='Salvar']"
export const decisionTimelineLink = "(//b[text()='Decisão'])[1]"
export const decisionDeleteButton = "//span[text()='Excluir']"
export const decisionDeleteBtnPopUp = "(//span[text()='Excluir'])[2]"

