
export const hoursPanel = "(//div[text()='Horas'])[1]"
export const timesheetEditPanel = "(//td[@class='ant-table-cell']//a)[1]"
export const datesAndRemarksHome = "//div[text()='Home']"
export const datesAndRemarksEdit = "(//button[@class='ant-btn'])[1]"
export const distributionDateInput = "(//div[@class='ant-picker-input']//input)[1]"
export const closingForecastInput = "(//div[@class='ant-picker-input']//input)[2]"
export const input_Input = "//input[@id='control-hooks_dtDataEntrada']"
export const observationsRemarks ="//textarea[@placeholder='Observações']"
//export const observationsRemarks ="//input[@id='control-hooks_dsObservacoes']"
export const okRemarksButton = "//button[@type='submit']"
export const forumNumberingAndAreaEdit = "(//button[@class='ant-btn']//span)[4]"
export const justiceTypeInput = "(//input[@role='combobox'])[4]"
export const justiceTypeOption = "(//div[@class='ant-select-item-option-content'])[2]"
export const justiceTypeButtonOk = "//span[normalize-space()='Salvar']"
export const justiceTypeTitle ="(//label[text()='Título']/following::input)[1]"
export const informationLink = "//div[text()='Informações']"
export const editButton = "//span[text()='Editar']"
export const addOrder = "//span[text()='Adicionar pedido']"
export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
export const timesheetOption = "//li[@role='menuitem']//span[contains(text(),'Horas')]"
export const professionalInput = "//input[@id='control-hooks_IDFuncionario']"
export const professional = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[2]"
export const timesheetDateInput = "//input[@id='control-hooks_DataExecucao']"
export const timesheetHourInput = "//input[@placeholder='Tempo']"
export const titleInput = "//input[@id='control-hooks_Titulo']"
export const nowButtonOk = "//button[@type='button']//span[contains(text(),'Ok')]"
export const clientInput = "//input[@id='control-hooks_IDCliente']"
export const client = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[3]"
export const timesheetClassificationInput ="//input[@id='control-hooks_IDClassificacao']"
export const legalInput = "//div[@title='Jurídico']//div[1]"
export const timesheetDescription = "//textarea[@id='control-hooks_Descricao']"
export const additionalInformationLink = "//span[@class='anticon anticon-right ant-collapse-arrow']//*[name()='svg']"
export const timesheetArea = "//input[@id='control-hooks_IDArea']"
export const specialtyArea= "//div[contains(text(),'Administração')]"
export const launchProgress = "//input[@type='checkbox']"
export const timesheetButtonOk = "//button[@class='ant-btn ant-btn-primary']//span[1]"
export const timesheetList = "(//b[text()='Timesheet'])[1]"
export const timesheetDeleteBtn = "//span[text()='Excluir']"
export const linkProgress = "(//b[text()='Andamento manual'])[1]"
export const timesheetEditPanelOk = "(//td[@class='ant-table-cell']//a)[1]"
export const faseOption = "//input[@id='control-hooks_cdFaseProcesso']"
export const archivedOption = "//div[text()='Arquivado']"
export const dateAndCitation = "//input[@id='control-hooks_dtDataCitacao']"
export const  valuesAndOrdersButtonSave = "//span[text()='Salvar']"

export const ritoInput = "//input[@id='control-hooks_idRito']"
export const incidentesOption = "//li[@title='Incidentes']"
export const incidentesgenericosOption = "//li[@title='Incidentes Genéricos (Cível, Trabalhista e Criminal)']"



