// export const inputType = "//input[@id='Tipo']"
// export const inputTypeOption = "//div[text()='Prazo']"
// export const freeTextCheckbox = "//span[@class='ant-checkbox']//input[1]"
// export const billingTitleInput = "(//label[text()='Título']/following::input)[1]"
// export const titleOption = "(//div[@class='ant-select-item-option-content'])[1]"
// export const dateInput = "(//input[@placeholder='Qual data?'])[1]"
// export const dateInputToday = "//a[contains(text(),'Hoje')]"
// export const scheduleHour = "//input[@placeholder='Hora inicial']"
// export const scheduleNow = "//li[@class='ant-picker-now']//a[1]"
// export const scheduleRemember = "(//label[text()='Lembrete']/following::input)[1]"
// export const scheduleRememberTime = "//div[text()='15 minutos']"
// export const scheduleLimiteDate = "(//input[@placeholder='Qual data?'])[2]"
// export const scheduleLimiteDateToday = "div#scrollable-area>div:nth-of-type(2)>div>div>div>div>div:nth-of-type(2)>a"
// export const scheduleTerminateTime = "/html[1]/body[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/form[1]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]"
// export const scheduleT = "//a[contains(text(),'Agora')]"
// export const scheduleExecuterInput = "//input[@id='FuncionarioExecutor']"
// export const scheduleExecuterOption = "//div[@id='scrollable-area']/div[5]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]"
// export const scheduleParts = "(//div[@class='ant-select-selector']//div)[1]"
// export const schedulePartsOption = "//div[text()='Adriana Cruz de Jesus']"
// export const scheduleDescription = "//textarea[@id='Observacao']"
// export const scheduleButtonSave = "//button[@type='submit']//span[1]"
// export const scheduleDeleteButton = "//span[text()='Excluir']"
// export const scheduleDeleteButtonPopUp = "(//span[text()='Excluir'])[2]"
 

