// export const linkCases = "(//a[@href='/cases'])[1]"
// export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
// export const scheduleOption = "//span[text()='Agenda']"
// export const tasksLink = "//div[text()='Tarefas']"
// export const listButton = "//span[text()='Lista']"
// export const calendarButton = "//span[text()='Calendário']"
// export const chevronRight = "//span[@class='fc-icon fc-icon-chevron-right']"
// export const courtHearing = "(//div[text()='Audiência Una'])[1]"
// export const deleteButtonSchedulePanel = "//span[text()='Excluir']"   

