/* ================================= Login Xpaths ===================================== */

export const checkboxCases ="div[class='ant-table-selection'] input[type='checkbox']"
export const authUser = "//input[@id='i0116']"
export const authUserButton = "//input[@id='idSIButton9']"
export const authPassword = "//input[@id='i0118']"
export const authButton = "//input[@id='idSIButton9']"
export const authCheck = "//input[@id='KmsiCheckboxField']"
export const authContinue = "//input[@id='idSIButton9']"
export const linkCases = "(//a[@href='/cases'])[1]"
export const firstElementTable = "(//td[@class='ant-table-cell']//a)[1]"
export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
export const saveButton = "//span[text()='Salvar']"
export const progressOption = "(//li[@class='ant-dropdown-menu-item']//span)[2]"
export const progressList = "(//b[text()='Andamento manual'])[1]"
export const timesheetOption = "//li[@role='menuitem']//span[contains(text(),'Horas')]"
export const timesheetList = "(//b[text()='Timesheet'])[1]"
export const buttonFilterThree = "(//button[@role='switch'])[3]"
export const timelineFilter = "//span[@aria-label='filter']//*[name()='svg']"
export const buttonFilter = "//span[text()='Filtrar']"
export const timesheetHoursPanel = "(//div[text()='Horas'])[1]"
export const timesheetEditPanel = "(//td[@class='ant-table-cell']//a)[1]"
export const decisionOption = "//span[text()='Decisão']"
export const buttonFilterOne = "(//button[@role='switch'])[1]"
export const decisionList = "(//b[text()='Decisão'])[1]"
export const scheduleList = "//b[normalize-space()='Prazo - Agenda']"
export const buttonFilterSix = "(//button[@role='switch'])[6]"
export const scheduleOption = "//span[text()='Agenda']"
export const guaranteeOption = "//span[text()='Garantia']"
export const guaranteeList = "(//b[text()='Garantia'])[1]"
export const buttonFilterGuarantee = "(//button[@class='ant-switch'])[5]"
export const InformationLink = "//div[text()='Informações']"
export const guaranteeLinkEdit ="(//div[@class='ant-table-content']//table)[2]/tbody[1]/tr[2]/td[8]/div[1]/div[3]/a[1]/span[1]"
export const guaranteeDeleteButtonPanel = "//span[contains(@class, 'anticon anticon-delete')]"
export const guaranteeMovementButton = "//span[@class='anticon anticon-file-add']"

