// export const casesSearchInput = "//input[@placeholder='Buscar caso']"
// export const casesSearchButton = "//button[@type='button']//span[@aria-label='search']//*[name()='svg']"
// export const FilterCasesIcon = "//span[@aria-label='filter']//*[name()='svg']"
// export const FilterStatusClosed = "//input[@value='closed']"
// export const selectACase = "(//input[@type='checkbox'])[2]"
// export const closeButton = "//span[@aria-label='file-excel']//*[name()='svg']"