export const casesSearchInput = "//input[@placeholder='Buscar caso']"
export const casesSearchButton = "//button[@type='button']//span[@aria-label='search']//*[name()='svg']"
export const FilterCasesIcon = "//span[@aria-label='filter']//*[name()='svg']"
export const FilterStatusClosed = "//input[@value='closed']"
export const selectACase = "(//input[@type='checkbox'])[2]"
export const closeButton = "//span[@aria-label='file-excel']//*[name()='svg']"
export const newCaseButton = "//span[text()='Novo caso']"
export const caseNumber ="//input[@id='numeroExterno']"
export const instanceSelect= "//input[@id='hierarquiaInstancia']"
export const instanceSelectOption= "(//div[@class='ant-select-item-option-content'])[1]"
export const statesInput = "//input[@id='hierarquiaPrimeiroNivel']"
export const statesOptions = "//li[@title='RJ']"
export const citiesOption = "//li[text()='Rio de Janeiro']"
export const forumInput = "//input[@id='cdNoForoVara']"
export const centralForumOption = "//li[@title='Fórum Central']"
export const centralForumOptionFirstInstance = "//li[text()='1ª Vara Cível']"
export const phaseInput = "//input[@id='idFase']"
export const phaseOption = "(//div[@class='ant-select-item-option-content'])[4]"
export const processType = "//input[@id='tituloProcesso']"
export const clientInput = "//input[@id='idCliente']"
export const clientOption = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[4]"
export const contractInput = "//input[@id='idContrato']"
export const contractOption = "//div[text()='62 - Contencioso Judicial | Cível | Ação Reivindicatória']"
export const customerEngagementInput = "//input[@id='envolvimentoCliente']"
export const customerEngagementOption = "//div[text()='Ativo']"
export const newPartButton = "//span[text()='Nova parte']"
export const distributionDateInput = "//input[@id='dataDistribuicao']"
export const entryDateInput = "//input[@id='dataEntrada']"
export const citationDateInput = "//input[@id='dataCitacao']"
export const currencySpecialInput = "//input[@id='nrMoedaInicialCausa']"
export const currencySpecialBRLOption = "//div[text()='BRL']"
export const riskEspecialInput = "//input[@id='risco']"
export const successSpecialInput = "//li[@title='Êxito']"
export const successSpecialOption = "//li[@title='Provável']"
export const causeValue= "//input[@id='valorCausa']"
export const predictedValue = "//input[@id='valorExpectativaApuracao']"
export const contingencyValue = "//input[@id='valorContingencia']"
export const responsibleSpecialInput = "//input[@id='idResponsavel']"
export const responsibleSpecialOption = "//div[text()='Adriana Cruz de Jesus']"
export const co_responsibleSpecialInput = "(//div[@class='ant-select-selector']//div)[1]"
export const co_responsibleSpecialInputOption = "(//div[text()='Alexandre Carneiro Rios das Neves'])[2]"
export const areaSpecialInpput = "//input[@id='idArea']"
export const areaSpecialInpputOption = "//div[text()='Administração']"
export const observationTextArea = "//input[@id='observacao']"
export const registerCaseButton = "//span[text()='Cadastrar caso']"
export const ritoHierarchyInput = "//input[@id='ritoHierarchy']"
export const riskEspecialOptionOne = "//li[@title='Incidentes']"
export const riskEspecialOptioTwo = "//li[text()='Incidentes Genéricos (Cível, Trabalhista e Criminal)']"
export const riskEspecialOptioThree = "//li[text()='Arguição de inconstitucionalidade']"




