// export const professionalInput = "//input[@id='control-hooks_IDFuncionario']"
// export const professional = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[2]"
// export const timesheetDateInput = "//input[@id='control-hooks_DataExecucao']"
// export const timesheetHourInput = "//input[@placeholder='Tempo']"
// export const titleInput = "//input[@id='control-hooks_Titulo']"
// export const nowButtonOk = "//button[@type='button']//span[contains(text(),'Ok')]"
// export const clientInput = "//input[@id='control-hooks_IDCliente']"
// export const client = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[4]"
// export const timesheetCase = "(//span[@class='ant-select-selection-search']/following-sibling::span)[3]"
// export const timesheetCaseOption = "//div[text()='9110 -  Ação de Exigir Contas']"
// export const timesheetClassificationInput ="//input[@id='control-hooks_IDClassificacao']"
// export const legalInput = "//div[@title='Jurídico']//div[1]"
// export const timesheetDescription = "//textarea[@placeholder='Descrição']"
// export const freeField = "(//label[text()='Título']/following::input)[2]"
// export const additionalInformationLink = "//span[@class='anticon anticon-right ant-collapse-arrow']//*[name()='svg']"
// export const timesheetArea = "//input[@id='control-hooks_IDArea']"
// export const specialtyArea= "(//div[text()='Cível'])[2]" 
// export const timesheetButtonOk = "//span[text()='Salvar']"
// export const timesheetList = "(//b[text()='Timesheet'])[1]"
// export const timesheetDeleteBtn = "//span[text()='Excluir']" 
// export const hoursPanel = "(//div[text()='Horas'])[1]"
// // export const timesheetEditPanel = "(//td[@class='ant-table-cell']//a)[1]"
// // export const timesheetHoursPanel = "(//div[text()='Horas'])[1]"
// export const DateEdit = "(//label[text()='Data']/following::input)[1]"
// export const Today = "//div[@class='ant-picker-footer']//a[1]"
// export const timesheetDeleteBtnPopUp = "(//span[text()='Excluir'])[2]"



