export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
export const timesheetOption = "//li[@role='menuitem']//span[contains(text(),'Horas')]"
export const professionalInput = "//input[@id='control-hooks_IDFuncionario']"
export const professional = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[2]"
export const timesheetDateInput = "//input[@id='control-hooks_DataExecucao']"
export const timesheetHourInput = "//input[@placeholder='Tempo']"
export const titleInput = "//input[@id='control-hooks_Titulo']"
export const nowButtonOk = "//button[@type='button']//span[contains(text(),'Ok')]"
export const clientInput = "//input[@id='control-hooks_IDCliente']"
export const client = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[3]"
export const timesheetCase = "(//span[@class='ant-select-selection-search']/following-sibling::span)[3]"
export const timesheetCaseOption = "//div[text()='9106 -  Apelação Cível']"
export const timesheetClassificationInput ="//input[@id='control-hooks_IDClassificacao']"
export const legalInput = "//div[@title='Jurídico']//div[1]"
export const timesheetDescription = "//textarea[@id='control-hooks_Descricao']"
export const additionalInformationLink = "//span[@class='anticon anticon-right ant-collapse-arrow']//*[name()='svg']"
export const timesheetArea = "//input[@id='control-hooks_IDArea']"
export const specialtyArea= "//div[contains(text(),'Administração')]" 
export const launchProgress = "//input[@type='checkbox']"
export const timesheetButtonOk = "//button[@class='ant-btn ant-btn-primary']//span[1]"
export const timesheetList = "(//b[text()='Timesheet'])[1]"
export const timesheetDeleteBtn = "//span[text()='Excluir']" 
export const linkProgress = "(//b[text()='Andamento manual'])[1]" 
export const hoursPanel = "(//div[text()='Horas'])[1]"
export const timesheetEditPanel = "(//td[@class='ant-table-cell']//a)[1]"

