export const progressOption = "(//li[@class='ant-dropdown-menu-item']//span)[2]"
export const progressClassificationInput = "(//div[contains(@class,'ant-select ant-select-single')]//div)[1]"
export const progressClassification = "(//span[@class='ant-select-selection-search']//input)[2]"
export const progressClassificationUpdate = "(//div[contains(@class,'ant-select-item ant-select-item-option')]//div)[2]"
export const progressDate = "//div[@class='ant-picker-input']//input[1]"
export const casesModelInput = "//label[text()='Modelo']/following::input" 
export const casesModel = "//div[text()='Diligência']"
export const casesTextArea = "//textarea[@class='ant-input']"
export const progressList = "(//b[text()='Andamento manual'])[1]"
export const progressDeleteBtn = "//span[normalize-space()='Excluir']"
export const saveButton = "//span[text()='Salvar']"
export const timesheetDeleteBtnPopUp = "(//span[text()='Excluir'])[2]"

