// export const InformationLink = "//div[text()='Informações']"
// export const InformationEdit = "//span[text()='Editar']"
// export const ValuesAndOrdersCurrencyOption = "(//span[text()='BRL'])[2]"
// export const BRLOption = "//div[text()='BRL']"
// export const RiskSelect = "//span[@class='ant-cascader-picker']//span[1]"
// export const likelySelect = "//li[@title='Provável']"
// export const valueOfTheCase = "(//label[text()='Valor da causa']/following::input)[1]"
// export const expectedValue = "(//label[text()='Valor previsto']/following::input)[1]"
// export const ContingenceValue = "(//label[text()='Valor de contingência']/following::input)[1]"