export const linkCases = "(//a[@href='/cases'])[1]"
export const firstElementTable = "(//td[@class='ant-table-cell']//a)[1]"
export const ValuesAndOrdersCurrencyOption = "(//span[text()='BRL'])[2]"
export const BRLOption = "//div[text()='BRL']"
export const RiskSelect = "//span[@class='ant-cascader-picker']//span[1]"
export const likelySelect = "//li[@title='Provável']"
export const valueOfTheCase = "(//label[text()='Valor da causa']/following::input)[1]"
export const expectedValue = "(//label[text()='Valor previsto']/following::input)[1]"
export const ContingenceValue = "(//label[text()='Valor de contingência']/following::input)[1]"
export const AddOrder = "//span[text()='Adicionar pedido']"
export const OrderItem = "(//span[@class='ant-select-selection-item'])[2]"
export const AccordingWork = "//div[@id='scrollable-area-table-request']/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/div[1]"
export const AddOrderButtonSave = "//span[text()='Salvar']"
export const addOrder = "//span[text()='Adicionar pedido']"