export const guaranteeType = "(//label[text()='Tipo de garantia']/following::input)[1]"
export const guaranteeItem = "//div[@title='Penhora']//div[1]"
export const guaranteeTextArea = "(//label[text()='Identificação']/following::textarea)[1]"
export const guaranteeSelectDate = "//input[@id='DataDeposito']"
export const guaranteeValue = "//input[@placeholder='Digite o valor da garantia']"
export const guaranteeCurrency = "//label[text()='Moeda']/following::input"
export const guaranteeReal = "//div[@title='BRL']//div[1]"
export const guaranteeDescription = "//textarea[@placeholder='Digite uma observação']"
export const guaranteeButtonSave = "//span[text()='Salvar']"

export const InformationLink = "//div[text()='Informações']"
export const guaranteeLinkEdit ="(//div[@class='ant-table-content']//table)[2]/tbody[1]/tr[2]/td[8]/div[1]/div[3]/a[1]/span[1]"
export const guaranteeDeleteButton = "//div[@id='__next']/main[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[5]/a[1]"
export const guaranteeMovementValue = "//input[@id='ValorMovimentacao']"
export const guaranteeTranferRadio = "(//input[@class='ant-radio-input'])[1]"
export const guaranteeTranferTo = "//input[@placeholder='Transferir à']"
export const guaranteeObservation = "//textarea[@placeholder='Digite uma observação']"
export const guaranteeButtonRadioObs = "(//label[text()='Observação']/following::input)[1]"
export const guaranteeDeleteButtonPopUp = "//span[text()='Excluir']"
export const guaranteeMovementDate = "//input[@placeholder='Selecionar data']"
export const paymentDate = "//input[@id='DataDeposito']"