// export const buttonNew = "//button[@class='ant-btn ant-btn-primary ant-dropdown-trigger']"
// export const guaranteeOption = "//span[text()='Garantia']"
// export const guaranteeType = "(//label[text()='Tipo de garantia']/following::input)[1]"
// export const guaranteeItem = "//div[@title='Penhora']//div[1]"
// export const guaranteeTextArea = "(//label[text()='Identificação']/following::textarea)[1]"
// export const guaranteeSelectDate = "//input[@placeholder='Selecionar data']"
// export const guaranteeValue = "//input[@placeholder='Digite o valor da garantia']"
// export const guaranteeCurrency = "//label[text()='Moeda']/following::input"
// export const guaranteeReal = "//div[@title='BRL']//div[1]"
// export const guaranteeDescription = "//textarea[@placeholder='Digite uma observação']"
// export const guaranteeButtonSave = "//span[text()='Salvar']"

// export const InformationLink = "//div[text()='Informações']"
// export const guaranteeLinkEdit ="(//div[@class='ant-table-content']//table)[2]/tbody[1]/tr[2]/td[8]/div[1]/div[3]/a[1]/span[1]"
// export const guaranteeDeleteButton = "//span[@class='anticon anticon-delete']"
// export const guaranteeMovementButton = "//span[@class='anticon anticon-file-add']"
// export const guaranteeMovementValue = "//input[@placeholder='Digite o valor da movimentação']"
// export const guaranteeTranferRadio = "(//input[@class='ant-radio-input'])[1]"
// export const guaranteeTranferTo = "//input[@placeholder='Transferir à']"
// export const guaranteeObservation = "//textarea[@placeholder='Digite uma observação']"
// export const guaranteeButtonRadioObs = "(//label[text()='Observação']/following::input)[1]"